//writes current configuration to some config in argument0
file = 'data\cfg\'+string(argument0);
cfg = file_text_open_write(file);
con_add(':: Сохраняем конфиг ' + string(file) + '...');
file_text_write_string(cfg, 'sv_map ' + string(global.sv_map));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_name ' + string(global.sv_name));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_maxplayers ' + string(global.sv_maxplayers));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_use_pwd ' + string(global.sv_use_pwd));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_password ' + string(global.sv_password));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_lan ' + string(global.sv_lan));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_rcon ' + string(global.sv_rcon));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_rcon_pwd ' + string(global.sv_rcon_pwd));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_ipbans ' + string(global.sv_ipbans));
file_text_writeln(cfg);
file_text_write_string(cfg, 'sv_cycle_maps ' + string(global.sv_cycle_maps));
file_text_writeln(cfg);
file_text_write_string(cfg, 'cl_timeout ' + string(global.cl_timeout));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_fraglimit ' + string(global.mp_fraglimit));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_timelimit ' + string(global.mp_timelimit));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_respawn ' + string(global.mp_respawn));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_itemrespawn ' + string(global.mp_itemrespawn));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_items ' + string(global.mp_items));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_powerups ' + string(global.mp_powerups));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_knockback ' + string(global.mp_knockback));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_selfdamage ' + string(global.mp_selfdamage));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_oldaim ' + string(global.mp_oldaim));
file_text_writeln(cfg);
file_text_write_string(cfg, 'mp_itemdrop ' + string(global.mp_oldaim));
file_text_writeln(cfg);
file_text_write_string(cfg, 'bot_names ' + string(global.bot_names));
file_text_writeln(cfg);
file_text_write_string(cfg, 'bot_chatter ' + string(global.bot_chatter));
file_text_writeln(cfg);
file_text_write_string(cfg, 'bot_tickrate ' + string(global.bot_tickrate));
file_text_writeln(cfg);
file_text_write_string(cfg, 'bot_randrate ' + string(global.bot_randrate));
file_text_writeln(cfg);
file_text_write_string(cfg, 'bot_cowardly ' + string(global.bot_cowardly));
file_text_close(cfg);
con_add(':: Сохранен конфиг ' + string(file) + '.');
